'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Zap, Eye, EyeOff, Loader2, AlertCircle } from 'lucide-react';
import { useAuthStore } from '@/store/authStore';
import { login } from '@/services/api/endpoints';

export default function LoginPage() {
  const router=useRouter(); const {setAuth}=useAuthStore();
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const submit=async(e:React.FormEvent)=>{e.preventDefault(); if(!email||!password){setError('Completa todos los campos.');return;} setLoading(true);setError(''); try{const r=await login(email,password); setAuth(r.user as any,r.token); router.push(r.user.rol==='admin'?'/admin/dashboard':'/rider/mi-estado');}catch(err:any){setError(err.response?.data?.error||err.message||'No se pudo conectar con el backend.');}finally{setLoading(false)}};
  return <main className="min-h-screen flex items-center justify-center bg-[#141414] px-4"><div className="w-full max-w-md"><div className="surface-glass rounded-2xl p-8 shadow-2xl"><div className="flex flex-col items-center mb-8"><div className="w-14 h-14 rounded-2xl bg-[#C0001A] flex items-center justify-center mb-4"><Zap className="w-7 h-7 text-white fill-white"/></div><h1 className="text-2xl font-bold text-white">MotoLeasing</h1><p className="text-sm text-[#666] mt-1">Plataforma de gestión de leasings</p></div><form onSubmit={submit} className="space-y-5"><div><label className="text-xs font-semibold text-[#A0A0A0] uppercase">Correo electrónico</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" className="w-full mt-1.5 px-4 py-3 rounded-xl bg-[#141414]/80 border border-white/10 text-white" placeholder="admin@motoleasing.com"/></div><div><label className="text-xs font-semibold text-[#A0A0A0] uppercase">Contraseña</label><div className="relative mt-1.5"><input value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} className="w-full px-4 py-3 pr-11 rounded-xl bg-[#141414]/80 border border-white/10 text-white" placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#666]">{show?<EyeOff/>:<Eye/>}</button></div></div>{error&&<div className="flex gap-2 p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400 text-sm"><AlertCircle className="w-4 h-4 shrink-0"/>{error}</div>}<button disabled={loading} className="w-full py-3 rounded-xl bg-[#C0001A] text-white font-semibold disabled:opacity-60">{loading?<><Loader2 className="inline w-4 h-4 animate-spin mr-2"/>Conectando…</>:'Ingresar'}</button></form><div className="mt-6 pt-5 border-t border-white/10 grid grid-cols-2 gap-2"><button onClick={()=>{setEmail('admin@motoleasing.com');setPassword('admin123')}} className="py-2 rounded-lg text-xs border border-white/10 text-[#A0A0A0]">Admin demo</button><button onClick={()=>{setEmail('rider@gmail.com');setPassword('rider123')}} className="py-2 rounded-lg text-xs border border-white/10 text-[#A0A0A0]">Rider demo</button></div></div></div></main>;
}
